project:
  type: website
  output-dir: docs
  render:
    - _sec_Chapter0_alphabet_pronunciation.qmd
    - _sec_Chapter1_Introductions.qmd
website:
  title: "Lisan Project"
  navbar:
    background: "#800000"
    left:
      - text: "<i class='bi bi-house-door'></i> Home"
        href: index.qmd
      - text: "Course Material"
        href: course-material.qmd
    right:
      - icon: github
        href: https://github.com/LisanProject/Somali-101
        aria-label: GitHub

  sidebar:
    style: floating
    collapse-level: 2   # Automatically collapses at level 2 headings
    contents:
      - href: Content/_sec_Chapter0_alphabet_pronunciation.html
        text: "0 Xarafka iyo Laxanka – Somali Alphabet and Pronunciation"
      - href: Content/_sec_Chapter1_Introductions.html
        text: "1 Isbarasho – Introducing Yourself"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-overflow: wrap